apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: provisioning-service
  annotations:
    github.com/project-slug: rchandrasekhar/provisioning-service
spec:
  type: other
  lifecycle: unknown
  owner: guests
